name: Strategy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - scikit-learn==1.3.2
  - pip
  - pip:
      - streamlit
      - python-dotenv
      - openai==1.16.2
      - langchain==0.1.14
      - langchain-core==0.1.35
      - langchain-openai==0.0.8
      - langchain-community==0.0.21
      - langchain-huggingface
      - chromadb==0.4.24
      - grpcio==1.59.3
      - onnxruntime
      - pytesseract
      - sentence-transformers
      - numpy==1.26.4
      - pydantic>=2.6.0
      - pypdf
      - pymupdf
      - docx2txt
      - tqdm
      - tiktoken==0.5.1
      - requests
      - pyyaml
      - regex
      - torch==2.2.1 --index-url https://download.pytorch.org/whl/cpu
      - tesseract
      - rpds-py==0.18.1
      - referencing==0.35.1
      - jsonschema==4.22.0
      - grpcio>=1.63.2
      - scipy==1.11.4
