# ===============================================================
# rules_table_universal.yaml
# Áp dụng chung cho tất cả các bảng (financial, UW, retention, KPI, BSC, client list, delegation…)
# ---------------------------------------------------------------
# Mục tiêu:
# - Nhận diện và chuẩn hóa mọi dạng bảng (Excel, PDF, DOCX, image)
# - Giữ nguyên giá trị và cấu trúc
# - Giúp GPT chỉ chỉnh format/mô tả, không suy diễn nội dung
# - Tương thích vector store và các bước clean sau này
# ===============================================================

meta:
  version: 1.1
  type: "universal_table"
  description: >
    YAML dùng chung cho tất cả các bảng trong lĩnh vực bảo hiểm: bảng tài chính, guideline kỹ thuật,
    bảng hạn mức UW, retention, KPI, Balanced Scorecard, danh sách khách hàng, v.v.
    Không cho phép GPT suy luận hoặc dịch thuật sai ngữ cảnh.

# ---------------------------------------------------------------
# 1️⃣ Nhận diện loại bảng (để phân nhánh logic xử lý)
# ---------------------------------------------------------------
doc_classification:
  financial_keywords: ["Balance Sheet", "Statement", "Tài sản", "Vốn chủ sở hữu", "Doanh thu", "mã 110", "Số cuối năm"]
  technical_keywords: ["Retention", "UW", "Underwriting", "Treaty", "Authority", "Delegated", "Limit", "Risk", "Engineering", "Property"]
  management_keywords: ["Objective", "Indicator", "Goal", "Action", "Balanced Scorecard", "BSC", "KPI"]
  client_keywords: ["Customer", "Client", "Company name", "Parent company", "List", "Insured", "Account"]
  healthcare_keywords: ["Health", "CPH", "MDI", "PAI", "Medical"]

# ---------------------------------------------------------------
# 2️⃣ Chuẩn hóa tiêu đề cột (tự động map các cột phổ biến)
# ---------------------------------------------------------------
columns_standardization:
  - match: ["Class", "Loại hình", "Line of Business", "LOB"]
    rename: "Business Line"
  - match: ["Parent", "Parent company"]
    rename: "Parent Company"
  - match: ["Customer name", "Client name", "Tên khách hàng", "Insured name"]
    rename: "Customer / Insured Name"
  - match: ["Ultimate Net Retention", "UNR", "Retention"]
    rename: "Retention (UNR)"
  - match: ["Max. Net Retention", "Maximum Retention"]
    rename: "Maximum Retention"
  - match: ["XOL Treaty protection", "Protection type"]
    rename: "Treaty / Protection"
  - match: ["Objective", "Mục tiêu"]
    rename: "Objective / Goal"
  - match: ["Indicator", "KPI", "Indicator Name"]
    rename: "Indicator"
  - match: ["Goal", "Target", "Purpose"]
    rename: "Goal / Target"
  - match: ["Action", "Action plan", "Biện pháp"]
    rename: "Action / Measure"
  - match: ["Finance", "Financial"]
    rename: "Finance"
  - match: ["Internal process", "Process"]
    rename: "Internal Process"
  - match: ["Learning", "Growth", "Development"]
    rename: "Learning & Growth"
  - match: ["Discount", "Tỷ lệ chiết khấu"]
    rename: "Discount (%)"
  - match: ["Loss Ratio", "L/R"]
    rename: "Loss Ratio (%)"
  - match: ["Limit", "Limit of Liability", "Authority Limit"]
    rename: "Limit / Authority"
  - match: ["Position", "Person", "Name of person/position", "Title"]
    rename: "Person / Position"
  - match: ["Unit", "Đơn vị"]
    rename: "Unit"
  - match: ["Value", "Amount", "Số tiền"]
    rename: "Value / Amount"

# ---------------------------------------------------------------
# 3️⃣ Làm sạch dữ liệu văn bản / loại bỏ rác
# ---------------------------------------------------------------
text_cleanup:
  remove_patterns:
    - "^\s*$"                    # dòng trống
    - "Page\s+\d+"               # số trang
    - "^\W+$"                    # ký tự đặc biệt
    - "^\d{4}-\d{2}-\d{2}$"      # ngày tháng lẻ
  strip_characters:
    - "\u00A0"                   # non-breaking space
    - "\t"
    - "\r"
  normalize_spaces: true
  collapse_double_newlines: true
  merge_multiline_cells: true    # ghép ô xuống dòng trong Excel

# ---------------------------------------------------------------
# 4️⃣ Hướng dẫn GPT xử lý bảng
# ---------------------------------------------------------------
gpt_prompt:
  mode: "table_only"
  instruction: >
    Chỉ chỉnh sửa hoặc mô tả lại bảng theo dạng văn bản ngắn, giữ nguyên cấu trúc hàng-cột và giá trị.
    KHÔNG được suy diễn hoặc thêm nhận xét tài chính. 
    Nếu bảng là kỹ thuật (Retention, Authority, UW Manual), hãy giữ nguyên thuật ngữ và đơn vị.
    Nếu bảng là KPI hoặc BSC, chỉ mô tả quan hệ giữa các cột Objective – Indicator – Action.
    Nếu bảng là danh sách khách hàng, chỉ liệt kê tên và nhóm.
    Nếu bảng là tài chính, giữ nguyên số và đơn vị, không dịch đơn vị tiền.
  example_behavior:
    - "Đúng: 'Bảng liệt kê các hạn mức Authority theo từng vị trí, giá trị USD giữ nguyên.'"
    - "Sai: 'Công ty có khả năng tài chính mạnh...' → không được phép."

# ---------------------------------------------------------------
# 5️⃣ Chuẩn hóa số liệu và đơn vị
# ---------------------------------------------------------------
numeric_format:
  decimal_separator: "."
  thousand_separator: ","
  detect_currency: ["USD", "VND", "JPY", "EUR", "mio", "000"]
  preserve_negatives: true
  preserve_parentheses: true
  unify_units:
    - pattern: "(?i)mio"
      replace: "million"
    - pattern: "(?i)000"
      replace: "thousand"

# ---------------------------------------------------------------
# 6️⃣ Hỗ trợ đọc nhiều sheet (Excel)
# ---------------------------------------------------------------
excel_reader:
  include_all_sheets: true
  sheet_prefix: true
  merge_vertical_headers: true
  skip_empty_sheets: true

# ---------------------------------------------------------------
# 7️⃣ Xuất dữ liệu ra vector store
# ---------------------------------------------------------------
output_format:
  text_mode: "paragraph"
  table_mode: "tsv"
  include_metadata: true
  metadata_fields:
    - source_path
    - page
    - sheet_name
    - language
    - doc_type
    - table_detected
    - company
