version: 0.4

globals:
  # --- Đơn vị & schema mặc định ---
  currency: VND
  unit_multiplier: 1
  column_names:
    code:  code
    name:  name
    note:  note
    end:   end
    begin: begin

  # --- Phát hiện trang "có bảng BCTC" ---
  detection_tokens:
    must_have_any:
      - "Mã số"
      - "Chỉ tiêu"
      - "Số cuối năm"
      - "Số đầu năm"
      - "Tài sản"
      - "Nguồn vốn"
      - "Vốn chủ sở hữu"
      - "Kết quả hoạt động kinh doanh"
    nice_to_have:
      - "B01-DN"
      - "B01-DNPN"
      - "B02-DN"
      - "BCTC"
      - "Thuyết minh"
      - "As at"
      - "As of"
      - "Balance sheet"

  # --- Padding cho ROI bảng (để giữ dòng tiêu đề cột số) ---
  roi_pad_top: 120
  roi_pad_lr: 8

  # --- Biên cột theo % bề rộng trang (gợi ý khi cần ép cột X%) ---
  column_x_percent:
    five_cols:          # CODE | NAME | NOTE | END | BEGIN
      code:  [0.00, 0.09]
      name:  [0.09, 0.72]
      note:  [0.72, 0.80]
      end:   [0.80, 0.91]
      begin: [0.91, 1.00]
    four_cols:          # CODE | NAME | END | BEGIN
      code:  [0.00, 0.09]
      name:  [0.09, 0.78]
      end:   [0.78, 0.89]
      begin: [0.89, 1.00]

  # --- La mã & tiêu đề cấp (normalize nhẹ) ---
  roman_normalize:
    "VỊ": "VI"
    "lll": "III"
    "ll": "II"
    "I.": "I."
    "II.": "II."
    "III.": "III."
    "IV.": "IV."
    "V.": "V."
    "VI.": "VI."
    "VII.": "VII."

  # --- Alias mã số hay bị méo OCR (giữ an toàn) ---
  code_aliases:
    "329-1": "329.1"
    "329-2": "329.2"
    "329-3": "329.3"
    "1311":  "131.1"
    "1511":  "151.1"
    "1512":  "151.2"
    "1.511": "151.1"
    "1.512": "151.2"
  # (các alias khác của bạn giữ nguyên)

    # ⚠️ Không còn các alias mạo hiểm kiểu "154"->"151", "1411"->"141"

  # --- Alias TÊN (không dấu cũng khớp) ---
  name_aliases:
    "Tong tai san": "Tổng tài sản"
    "Nguon von": "Tổng nguồn vốn"
    "No phai tra": "Nợ phải trả"
    "Von CSH": "Vốn chủ sở hữu"
    "Tai san ngan han": "Tài sản ngắn hạn"
    "Tai san dai han": "Tài sản dài hạn"

  # --- Mã ↔ tên chuẩn để đối chiếu chéo (hint) ---
  code_name_pairs:
    "100": "Tài sản ngắn hạn"
    "200": "Tài sản dài hạn"
    "270": "Tổng tài sản"
    "300": "Nợ phải trả"
    "400": "Vốn chủ sở hữu"
    "440": "Tổng nguồn vốn"

  # --- Cây cha–con theo TÊN ---
  parent_children_by_name:
    "Tổng tài sản": ["Tài sản ngắn hạn", "Tài sản dài hạn"]
    "Tổng nguồn vốn": ["Nợ phải trả", "Vốn chủ sở hữu"]

  # --- Chuẩn hoá số Việt + vá lỗi OCR phổ biến (an toàn) ---
  number_cleanup:
    drop_chars: ["\u00A0", "\t", "£", "¥", "₫"]
    fix_patterns:
      - {from: "(?<=\\d)\\s+(?=\\d)", to: ""}                 # xoá space giữa chữ số
      - {from: "[\\.,]{2,}", to: "."}                         # chấm/phẩy lặp
      - {from: "(?<!\\d)[ZIlO](?=\\d)", to: ""}               # ký tự nhiễu đầu số
      - {from: "(?<=\\d),(?=\\d{3}(\\D|$))", to: "."}         # 1,234 → 1.234
      - {from: "\\((\\d[\\d\\.,]*)\\)", to: "-\\1"}           # (1.234) → -1.234
    thousand_grouping: true

  # --- Policy tự sửa khi validator thấy lệch ---
  autofix_policy:
    fix_parent_from_children: true
    fix_minor_digit_off_by: true
    fix_leading_extra_digit: true
    clamp_negative_where_forbidden: false   # để soft_checks quyết định nơi được âm

  # --- Lọc rác header/caption (nới, tránh xoá nhầm mục hợp lệ) ---
  drop_if_name_contains:
    - "bảng cân đối kế toán"
    - "mẫu số"
    - "ban hành theo"
    - "đơn vị tính"
    - "as at"
    - "as of"
    - "for the year ended"
    - "b01-dnpnt"
    - "b01-dn"
    - "bctc"
    - "trang "

  # --- Synonyms cho tiêu đề cột ---
  synonyms:
    end:   ["Số cuối năm","Năm nay","Current year"]
    begin: ["Số đầu năm","Năm trước","Prior year"]
    note:  ["Thuyết minh","TM","Ghi chú","Notes"]

  # --- Profile layout → map về schema logic (không ép 5 cột vật lý) ---
  layouts:
    L5:  {column_map: {code: 0, name: 1, note: 2, end: 3, begin: 4}}
    L4:  {column_map: {code: 0, name: 1, end: 2, begin: 3}, fill_missing: {note: null}}
    L3A: {column_map: {name: 0, end: 1, begin: 2}, infer_code_from_name: true}
    L3B: {column_map: {code: 0, name: 1, end: 2}, fill_missing: {begin: null, note: null}, assume_single_amount_is: "END"}

  # --- Công thức cross-check cho cả trang ---
  cross_formulas:
    - name: "Tài sản dài hạn"
      end:   "200 = 210 + 220 + 250 + 260"
      begin: "200 = 210 + 220 + 250 + 260"   # (đã sửa start -> begin)
    - name: "Tổng tài sản"
      end:   "270 = 100 + 200"
      begin: "270 = 100 + 200"

  # --- Cho phép override theo công ty (tuỳ chọn) ---
  company_overrides: {}

# =========================================================
# BẢNG CÂN ĐỐI KẾ TOÁN (B01-DN/B01-DNPN)
# =========================================================
balance_sheet:
  meta:
    side_by_side: ["assets", "equity_liab"]
    variant_hint: ["B01-DN", "B01-DNPN", "Balance sheet"]
  expected_order_increasing: true
  tolerate_missing_codes: true

  sections:
    assets:
      codes_expected:
        - 100
        - 110; 111; 112
        - 120; 121; 122; 123
        - 130; 131; 131.1; 131.2; 132; 133; 134; 135; 136; 137; 138; 139
        - 140; 141
        - 150; 151; 151.1; 151.2; 152
        - 190; 191; 192
        - 200
        - 210; 211; 212; 213; 214; 215; 216
        - 220; 221; 222; 223; 224; 225
        - 240; 241; 242; 243
        - 250; 251; 252
        - 260; 261; 262; 263
        - 270
      rules:
        - eq: ["110", ["111","112"]]
        - eq: ["120", ["121","122","123"]]
        - eq: ["130", ["131","131.1","131.2","132","133","134","135","136","137","138","-139"]]
        - eq: ["140", ["141"]]
        - eq: ["151", ["151.1","151.2"]]
        - eq: ["150", ["151","152"]]
        - eq: ["190", ["191","192"]]
        - eq: ["100", ["110","120","130","140","150","190"]]
        - eq: ["210", ["211","212","213","214","215","216"]]
        - eq: ["220", ["221","222","223","224","225"]]
        - eq: ["240", ["241","242","243"]]
        - eq: ["250", ["251","252"]]
        - eq: ["260", ["261","262","263"]]
        - eq: ["200", ["210","220","240","250","260"]]
        - eq: ["270", ["100","200"]]

        
      soft_checks:
        - non_negative: ["111","112","120","121","122","123","131","131.1","131.2","132","133","134","135","136","137","138","140","141","150","151","151.1","151.2","152","190","191","192","210","211","212","213","214","215","216","220","221","222","223","224","225","240","241","242","243","250","251","252","260","261","262","263"]
        - may_negative: ["139"]
        - same_value: [["140","141"]]
        - approx_eq: {left: "ratio(end, begin)", right: 1.0, tolerance_ratio: 0.5}

    equity_liab:
      codes_expected:
        - 300
        - 310; 311; 312; 313; 314; 315; 316; 317; 318
        - 320; 321; 322; 323; 324; 325; 326; 327; 328
        - 329; 329.1; 329.2; 329.3
        - 330
        - 400
        - 410; 411; 412; 413; 414; 415; 416
        - 420; 421; 422; 423; 424
        - 440
      rules:
        - eq: ["329", ["329.1","329.2","329.3"]]
        - eq: ["300", ["310","320","329","330"]]
        - eq: ["400", ["410","420"]]
        - eq: ["440", ["300","400"]]
      soft_checks:
        - non_negative: ["311","312","313","314","315","316","317","318","321","322","323","324","325","326","327","328","329","329.1","329.2","329.3","330","410","411","412","413","414","415","416","420","421","422","423","424"]
        - may_negative: ["421"]

  # Đối chiếu tổng theo MÃ và theo TÊN
  cross_sheet_rules:
    - eq: ["assets.270", ["equity_liab.440"]]
  cross_sheet_rules_by_name:
    - equals:
        left:  "Tổng tài sản"
        right: "Tổng nguồn vốn"

# =========================================================
# KQ HOẠT ĐỘNG KINH DOANH – KHỐI BẢO HIỂM
# =========================================================
income_statement_insurance:
  tolerate_missing_codes: true
  codes_expected:
    - 01; 01.1; 01.2; 01.3
    - 02; 02.1; 02.2
    - 03
    - 04; 04.1; 04.2
    - 10
    - 11; 11.1; 11.2
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17; 17.1; 17.2
    - 18
    - 19
  rules:
    - eq: ["01", ["01.1","01.2","-01.3"]]
    - eq: ["02", ["02.1","-02.2"]]
    - eq: ["03", ["01","-02"]]
    - eq: ["04", ["04.1","04.2"]]
    - eq: ["10", ["03","04"]]
    - eq: ["11", ["11.1","-11.2"]]
    - eq: ["15", ["11","-12","13","-14"]]
    - eq: ["17", ["17.1","17.2"]]
    - eq: ["18", ["15","16","17"]]
    - eq: ["19", ["10","-18"]]
  soft_checks:
    - non_negative: ["01.1","01.2","03","04","04.1","04.2","10","12"]
    - may_negative: ["13","14","16"]

# =========================================================
# KQ KINH DOANH – TỔNG HỢP
# =========================================================
income_statement_total:
  tolerate_missing_codes: true
  codes_expected:
    - 19
    - 23; 24; 25
    - 26
    - 30
    - 31; 32; 40
    - 50; 51; 52; 60
  rules:
    - eq: ["25", ["23","-24"]]
    - eq: ["30", ["19","25","-26"]]
    - eq: ["40", ["31","-32"]]
    - eq: ["50", ["30","40"]]
    - eq: ["60", ["50","-51","-52"]]
  soft_checks:
    - may_negative: ["25","30","40","60"]

# =========================================================
# (Tuỳ chọn) Doanh thu theo nghiệp vụ → khớp mã 03
# =========================================================
revenue_by_line:
  lines:
    - code: DV_XECO
    - code: DV_TAISAN
    - code: DV_HANGHAI
    - code: DV_SUC_KHOE
    - code: DV_CHAY_NO
    - code: DV_KHAC
  fields: [written_premium, inward_reinsurance, outward_reinsurance, change_uep, net_premium]
  rules:
    - eq: ["net_premium", ["written_premium","inward_reinsurance","-outward_reinsurance","-change_uep"]]
  cross_checks:
    - equals:
        left:  "sum(lines[*].net_premium)"
        right: "income_statement_insurance.03"
