---
# =========================================================
# YAML CLEAN CHO VĂN BẢN (TEXT) — dùng với apply_yaml_clean(..., mode="text")
# Tập trung loại header/footer, rác OCR, gộp khoảng trắng; KHÔNG đụng tới số
# =========================================================
version: 0.4

globals:
  text_cleanup:
    # 1) Ký tự rác phổ biến trong scan/PDF
    drop_chars:
      - "\u00A0"   # non-breaking space
      - "¦"
      - "•"
      - ""
      - ""
      - "∙"
      - "·"
      - "│"
      - "┃"
      - "丨"

    # 2) Mẫu thay thế / xoá theo regex (toàn cục)
    #    Lưu ý: code sẽ chạy re.sub tuần tự theo thứ tự dưới đây
    fix_patterns:
      # --- dọn header/footer & meta của biểu mẫu ---
      - from: "(?mi)^.*\\b(Mẫu\\s*số|Mau\\s*so)\\b.*$\\n?"
        to: ""
      - from: "(?mi)^.*\\b(B01\\s*-?\\s*DN(P|PN)?T?)\\b.*$\\n?"
        to: ""
      - from: "(?mi)^.*\\b(B02\\s*-?\\s*DN)\\b.*$\\n?"
        to: ""
      - from: "(?mi)^.*\\b(BCTC|Báo\\s*cáo\\s*tài\\s*chính|Bao\\s*cao\\s*tai\\s*chinh)\\b.*$\\n?"
        to: ""
      # Chỉ xoá dòng có 'Đơn vị...' kèm VND (giảm xoá nhầm nội dung)
      - from: "(?mi)^.*\\b(Đơn\\s* vị(\\s*tính)?|Don\\s*vi(\\s*tinh)?)\\b.*VND.*$\\n?"
        to: ""
      - from: "(?mi)^.*\\b(Ban\\s*hành\\s*theo|Ban\\s*hanh\\s*theo)\\b.*$\\n?"
        to: ""
      - from: "(?mi)^.*\\b(As\\s+at|As\\s+of|For\\s+the\\s+year\\s+ended)\\b.*$\\n?"
        to: ""
      - from: "(?mi)^\\s*(Trang|Page)\\s*\\d+\\s*$\\n?"
        to: ""

      # --- dòng kẻ, gạch ngang, chữ trang trí ---
      - from: "(?m)^[ \\t]*[-_]{3,}.*$\\n?"
        to: ""
      - from: "(?m)^[ \\t]*={3,}.*$\\n?"
        to: ""

      # --- nối từ bị ngắt dòng bằng dấu gạch ngang (hyphenation) ---
      - from: "(?<!\\d)-\\s*\\n\\s*(?=[A-Za-zÀ-ỹĐđ])"
        to: ""
      # --- xoá khoảng trắng thừa trước ngắt dòng ---
      - from: "[ \\t]+\\n"
        to: "\n"

      # --- chuẩn hoá dấu cách & khoảng trắng ---
      - from: "[\\t ]{2,}"
        to: " "
      - from: "\\u200b|\\u200c|\\u200d"   # zero-width chars
        to: ""

      # --- dọn các cặp ký tự OCR lẫn lộn hay gặp ---
      - from: "I\\s*\\|\\s*I"   # I | I  → II
        to: "II"
      - from: "\\bll\\b"
        to: "II"
      - from: "\\blll\\b"
        to: "III"

      # --- gom các dấu gạch đầu dòng lạ về dấu "-" chuẩn ---
      - from: "[•●◦▪▫►■□◆◇¤·]"
        to: "-"

      # --- nén nhiều dòng trống liên tiếp còn 1 ---
      - from: "(?m)^(?:\\s*\\n){3,}"
        to: "\n\n"
