# =========================
# UI THEME & LAYOUT (YAML)
# =========================
# MẸO: Thay đổi giá trị bên phải rồi lưu — không cần sửa code Python.

# ========= LOGO & TIÊU ĐỀ =========
LOGO_IS_VIDEO: true                 # true = logo là video MP4; false = ảnh PNG/JPG
LOGO_SIZE_PX: 70                    # kích thước logo (rộng = cao, px)
LOGO_BORDER_RADIUS_PX: 0            # 0 = vuông; 50 = bo tròn nhiều
LOGO_OBJECT_FIT: "contain"          # "contain" (không cắt) | "cover" (có thể cắt cho đủ khung)
LOGO_SHADOW: false                  # đổ bóng quanh logo (true/false)
LOGO_OFFSET_REM: 0                  # dịch logo theo trục dọc (+ xuống, - lên)

TITLE_FONT_SIZE_REM: 2.2            # cỡ chữ tiêu đề chính @TOMTRANCHATBOT (rem)

# ========= KÍCH THƯỚC & BỐ CỤC =========
HEADER_TO_CHAT_GAP_REM: -0.6   # kéo khối chat lên gần giữa
INPUT_MARGIN_TOP_REM: -20    # đẩy ô nhập lên mạnh hơn (có thể chỉnh -10 → -14)


# ========= BANNER / ĐƯỜNG KẺ DƯỚI HEADER =========
HEADER_DIVIDER_MODE: "text"         # "text" = chữ + 2 vạch; "line" = chỉ vạch
HEADER_DIVIDER_TEXT: "Hãy hỏi tôi về chiến lược hay bất cứ điều gì"  # để trống = không hiện chữ

HEADER_DIVIDER_TOP_REM: 0        # tăng = banner cách logo xa hơn
HEADER_DIVIDER_BOTTOM_REM: 0    # tăng = khoảng trống bên dưới banner lớn hơn
HEADER_DIVIDER_WIDTH_PCT: 20       # % bề ngang banner (cả cụm chữ + vạch)
HEADER_DIVIDER_THICK_PX: 0          # độ dày vạch
HEADER_DIVIDER_STYLE: solid         # solid | dashed | dotted
HEADER_DIVIDER_COLOR: "#00000000"     # màu vạch (rất nhạt cho nền trắng)

# chữ ở giữa banner
HEADER_DIVIDER_TEXT_COLOR: "#111827"     # màu chữ banner (xám nhạt)
HEADER_DIVIDER_TEXT_SIZE_REM: 0.95       # cỡ chữ banner (rem)
HEADER_DIVIDER_TEXT_WEIGHT: 600          # độ đậm: 400=thường, 600=semibold, 700=bold
SIDEBAR_TOGGLE_ENABLED: true

# ========= KÍCH THƯỚC & BỐ CỤC =========
# Khoảng cách từ header xuống khung chat (có thể âm để kéo lên)
HEADER_TO_CHAT_GAP_REM: 0.4

# Chiều cao khung chat (desktop). Nếu cần tách theo trạng thái, giữ các khóa *_EMPTY/NONEMPTY bên dưới.
CHAT_HEIGHT_VH_DESKTOP: 68          # % chiều cao viewport cho khung chat (desktop)
CHAT_HEIGHT_VH_EMPTY: 15            # KHÔNG dùng trong CSS mới; giữ lại để tương thích code cũ
CHAT_HEIGHT_VH_NONEMPTY: 15         # KHÔNG dùng trong CSS mới; giữ lại để tương thích code cũ

# Đệm bên trong khung chat
CHAT_PAD_V_REM: 1.1                 # đệm trên/dưới (rem)
CHAT_PAD_H_REM: 1.6                 # đệm trái/phải (rem)

# Bề rộng tối đa khung chat
CHAT_WIDTH_DESKTOP_PX: 750          # desktop (px)
CHAT_WIDTH_TABLET_PX: 680           # tablet (px)
CHAT_WIDTH_MOBILE_PCT: 92           # mobile (% theo bề ngang màn hình)

# configs/ui_streamlit_theme.yaml hoặc file cấu hình runtime của bạn
GPT_SCOPE: "tables"   # "tables" | "all"


# ========= Ô nhập =========
INPUT_MARGIN_TOP_REM: -5          # âm = kéo ô nhập lên sát khung chat; dương = đẩy xuống
INPUT_BG:   "#F9FAFB"          # nền xám rất nhạt (thay cho xanh)
INPUT_TEXT: "#111827"
INPUT_BORDER_DARK: "#9CA3AF"   # viền xám trung tính (thay cho đỏ/xanh)


# Sidebar trái
LEFT_SIDEBAR_WIDTH_PX: 290          # độ rộng sidebar trái (px)

# ========= STRAP (dòng thương hiệu giữa trang) =========
SHOW_STRAP: true
STRAP_ICON: "🧭"
STRAP_TEXT: "The Best Strategy Assistant of Tom Tran"
FOOTER_STRAP_TOP_MARG_REM: 0.10     # khoảng cách strap với phần trên

# ========= FOOTER =========
SHOW_FOOTER: true
FOOTER_TITLE: "© TOMTRAN Chatbot"
FOOTER_TAGLINE: "Strategic insight & business intelligence."
FOOTER_COPYRIGHT: "© 2025 Tom Tran Corporation. All rights reserved."
FOOTER_BRAND_TOP_MARG_REM: 0.35

# ========= THEME =========
THEME_BASE: "light"                 # "light" | "dark" (dành cho widget mặc định của Streamlit)
BG_COLOR:   "#FFFFFF"               # nền trang (app + content)
CARD_COLOR: "#FFFFFF"               # nền thẻ / vùng chat / sidebar
TEXT_COLOR: "#111827"               # màu chữ chính (xám đậm)
LINE_COLOR: "#E5E7EB"               # đường kẻ / viền phân tách (rất nhạt)

# Bong bóng chat
BUBBLE_USER_BG: "#E5F1FF"           # nền bong bóng user (xanh rất nhạt)
BUBBLE_BOT_BG:  "#F3F4F6"           # nền bong bóng bot (xám rất nhạt)



# có thể thêm key mới nếu bạn muốn:
INPUT_BORDER_DARK: "#6B7280"

# Prompt gợi ý dưới header
PROMPT_TEXT: "#111827"              # màu chữ prompt gợi ý
PROMPT_FONT_SIZE_REM: 1.20          # cỡ chữ prompt gợi ý (rem)

# CHỈNH FOOTER
FOOTER:
  ENABLED: true                # false = ẩn footer
  TEXT_HTML: |
    <a href="https://www.flaticon.com/free-stickers/chile" title="chile stickers">
      Chile stickers created by Stickers - Flaticon
    </a>
    The best intelligent assistant for <strong>Tom Tran</strong>

  ALIGN: "center"               # left | center | right

  COLOR: "#6B7280"             # mã màu chữ
  SIZE_REM: 0.9                # cỡ chữ
  SHOW_HR_TOP: true            # kẻ 1 đường ngang phía trên
  SHOW_HR_BOTTOM: false        # kẻ 1 đường ngang phía dưới
  HR_COLOR: "#E5E7EB"          # màu đường kẻ
  HR_THICK_PX: 1               # độ dày đường kẻ
  MARGIN_TOP_REM: 0.6          # khoảng cách trên của dòng footer
  MARGIN_BOTTOM_REM: 0.0       # khoảng cách dưới
