# ui_streamlit_theme.yaml
META:
  VERSION: 2.2
  NOTES: "Điều khiển UI như ChatGPT; mọi tùy chỉnh làm ở YAML."

OBJECTS_INDEX:
  SIDEBAR: "Cột trái (menu, điều khiển)"
  CHAT_PANEL: "Cột chat (khung nội dung giống ChatGPT)"
  CHAT_INPUT: "Ô nhập tin nhắn (pill ở dưới/giữa khi rỗng)"
  BUBBLE_USER: "Bong bóng tin người dùng"
  BUBBLE_BOT: "Bong bóng tin bot"

CENTER_AXIS:
  ENABLED: true
  MODE: viewport
  X_PCT: 50
  Y_PCT: 50
  SNAP_TO_GRID: false
  GRID_STEP_PX: 8

COLORS:
  BG:   "#FFFFFF"
  TEXT: "#1F2328"
  CARD: "#FFFFFF"
  LINE: "#E5E7EB"
  PRIMARY: "#10A37F"

TYPOGRAPHY:
  FONT_FAMILY: "Inter, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial"
  BASE_SIZE_PX: 15
  TITLE_SIZE_PX: 20
  LINE_HEIGHT: 1.55

LAYERS:
  BASE: 0
  HEADER: 80
  CHAT: 100
  SIDEBAR: 500
  DIVIDER: 210
  INPUT: 100
  OVERLAY: 950
  TOGGLE: 10000

LAYOUT:
  MAIN_MAX_WIDTH_PCT: 100
  GUTTER_PX: 0
  SIDEBAR_WIDTH_PCT: 22     # gần ChatGPT
  CHAT_WIDTH_PCT: 78
  DIVIDER:
    SHOW: true
    COLOR: "#EEF2F7"
    STYLE: "solid"
    WIDTH_PX: 1
    OFFSET_X_PX: 0

EFFECTS:
  SHADOW: false
  BLUR_PX: 0

OBJECTS:
  SIDEBAR:
    ENABLED: true
    Z_INDEX: 220
    OFFSET_X: "0px"         # Đặt 0 để sidebar không “trôi” mất
    OFFSET_Y: "0px"
    BG: "#0F172A"
    TEXT: "#E2E8F0"
    BORDER_COLOR: "#0F172A"
    BORDER_PX: 0
    RADIUS_PX: 0
    SHADOW: false
    PADDING_PX: 14
    AXIS:
      INHERIT: true
      MODE: inherit
      X_PCT: 50
      Y_PCT: 50
      OFFSET_X_PX: 0
      OFFSET_Y_PX: 0
      SCALE_X: 1.0
      SCALE_Y: 1.0
    DIVIDER:
      USE_LOCAL: true
      SHOW: true
      Z_INDEX: 230
      BASE_ON_AXIS: true
      OFFSET_X_PX: 0
      COLOR: "#EEF2F7"
      STYLE: "solid"
      WIDTH_PX: 1
      ORIGIN_EDGE: "right"

  CHAT_PANEL:
    ENABLED: true
    Z_INDEX: 110
    OFFSET_X: "0px"
    OFFSET_Y: "0px"
    BG: "#FFFFFF"
    TEXT: "#1F2328"
    BORDER_COLOR: "#FFFFFF"
    BORDER_PX: 0
    RADIUS_PX: 0
    SHADOW: false
    PADDING_PX: 0
    CHAT_MAX_WIDTH_PX: 880
    CHAT_HEIGHT_VH_DESKTOP: 72
    CHAT_HEIGHT_VH_MOBILE: 68
    AXIS:
      INHERIT: true
      MODE: inherit
      X_PCT: 50
      Y_PCT: 50
      OFFSET_X_PX: 0
      OFFSET_Y_PX: 0
      SCALE_X: 1.0
      SCALE_Y: 1.0

  CHAT_INPUT:
    ENABLED: true
    Z_INDEX: 900
    WIDTH_PCT: 100
    OFFSET_X: "0px"
    OFFSET_Y: "0px"
    EMPTY_OFFSET_VH: -30
    BG: "#F7F7F8"
    BORDER_COLOR: "#E5E7EB"
    BORDER_PX: 1
    RADIUS_PX: 999
    STICKY_BOTTOM_PX: 20
    AXIS:
      INHERIT: true
      MODE: inherit
      X_PCT: 50
      Y_PCT: 50
      OFFSET_X_PX: 0
      OFFSET_Y_PX: 0
      SCALE_X: 1.0
      SCALE_Y: 1.0

  BUBBLE_USER:
    ENABLED: true
    BG: "#E7F0FF"
    TEXT: "#0B1520"
    BORDER_COLOR: "#DCE6FF"
    BORDER_PX: 1
    RADIUS_PX: 16

  BUBBLE_BOT:
    ENABLED: true
    BG: "#FFFFFF"
    TEXT: "#0B1520"
    BORDER_COLOR: "#E5E7EB"
    BORDER_PX: 1
    RADIUS_PX: 16

COMPONENTS:
  HIDE_STREAMLIT_CHROME: false
  EMPTY_STATE:
    SHOW: true
    TITLE_HTML: "Bạn đang làm về cái gì?"
    SUB_HTML: "Hỏi bất kỳ điều gì…"

SIDEBAR_CONTENT:
  SHOW: true
  SECTIONS:
    - type: new_chat_button
      label: "Đoạn chat mới"
    - type: history
      label: "Lịch sử đoạn chat"
    - type: spacer
    - type: slider
      label: "Temperature"
      min: 0.0
      max: 1.0
      step: 0.05
      value: 0.3
    - type: slider
      label: "Top-p"
      min: 0.1
      max: 1.0
      step: 0.05
      value: 1.0
    - type: toggle
      label: "Fallback"
      value: true
    - type: number
      label: "Retriever k"
      min: 1
      max: 20
      step: 1
      value: 6
    - type: slider
      label: "Min relevance"
      min: 0.0
      max: 1.0
      step: 0.01
      value: 0.25
